### ISSUE TITLE
Change to public

### ISSUE THREAD

**Issue by Sonderwoods** [mcneel/Rhino.Testing#7]
https://github.com/mcneel/Rhino.Testing/blob/bb2c62f05a3add15b5ea647abe3233246ea23620/src/Grasshopper/GH1Runner.cs#L55

I would love to change this method to public so i can make my own checks in the GH document. This will add an extra layer of testing than locking me to outputting true into Bake Context components.

**Comment by eirannejad** [comment]
Implemented in `8.0.23-beta`
See https://github.com/mcneel/Rhino.Testing?tab=readme-ov-file#testing-grasshopper-files
